/**
 * Generates an OpenClaw YAML config string from the given options.
 * This is the pure logic extracted from the UI for testability.
 */
export interface ConfigOptions {
	agentName: string;
	agentDescription?: string;
	agentVersion?: string;
	memoryBackend: 'none' | 'sqlite' | 'postgres' | 'redis';
	memoryPath?: string;
	memoryUrl?: string;
	scheduleType: 'none' | 'interval' | 'cron' | 'event';
	scheduleValue?: string;
	enabledTools: string[];
	logLevel: 'debug' | 'info' | 'warn' | 'error';
	logFile?: string;
	maxRetries?: number;
}

export function generateYaml(opts: ConfigOptions): string {
	const lines: string[] = [];

	lines.push(`# OpenClaw Agent Configuration`);
	lines.push(`# Generated by botfil.es`);
	lines.push(``);
	lines.push(`agent:`);
	lines.push(`  name: "${opts.agentName}"`);
	if (opts.agentDescription) lines.push(`  description: "${opts.agentDescription}"`);
	lines.push(`  version: "${opts.agentVersion ?? '1.0.0'}"`);
	lines.push(``);

	lines.push(`memory:`);
	lines.push(`  backend: ${opts.memoryBackend}`);
	if (opts.memoryBackend === 'sqlite' && opts.memoryPath) {
		lines.push(`  path: "${opts.memoryPath}"`);
	} else if ((opts.memoryBackend === 'postgres' || opts.memoryBackend === 'redis') && opts.memoryUrl) {
		lines.push(`  url: "${opts.memoryUrl}"`);
	}
	lines.push(``);

	lines.push(`schedule:`);
	lines.push(`  type: ${opts.scheduleType}`);
	if (opts.scheduleType === 'cron' && opts.scheduleValue) {
		lines.push(`  cron: "${opts.scheduleValue}"`);
	} else if (opts.scheduleType === 'interval' && opts.scheduleValue) {
		lines.push(`  seconds: ${opts.scheduleValue}`);
	} else if (opts.scheduleType === 'event' && opts.scheduleValue) {
		lines.push(`  event: "${opts.scheduleValue}"`);
	}
	lines.push(``);

	lines.push(`tools:`);
	if (opts.enabledTools.length === 0) {
		lines.push(`  enabled: []`);
	} else {
		lines.push(`  enabled:`);
		opts.enabledTools.forEach((t) => lines.push(`    - ${t}`));
	}
	lines.push(``);

	lines.push(`logging:`);
	lines.push(`  level: ${opts.logLevel}`);
	if (opts.logFile) lines.push(`  file: "${opts.logFile}"`);
	lines.push(``);

	lines.push(`runtime:`);
	lines.push(`  max_retries: ${opts.maxRetries ?? 3}`);

	return lines.join('\n');
}
